<?php
const PASSWORD_HASH_ALGORITHM = PASSWORD_DEFAULT;
const DATE_FORMAT = "Y-m-d H:i:s";
const THUMBNAIL_DESTINATION =IMAGE_PATH ;
const THUMBNAIL_URL_PREFIX = "img";
const RANDOM_DIRECTORY_NAME_LENGTH = 8 ;
